/* PowerUp 单词库 v2 —— 对标剑桥 Power Up 1/2 教材单元 + YLE Starters/Movers 考纲词
 * 结构: WORD_BANK[level].units[unitKey] = { title, words: [{en, zh}] }
 * 约束: 全库 en 唯一、zh 唯一（避免配对歧义）
 */
(function (root) {
  var WORD_BANK = {
    L1: {
      title: "一级 Level 1",
      units: {
        S: {
          title: "基础：问候·颜色·数字·身体",
          words: [
            { en: "hello", zh: "你好" },
            { en: "hi", zh: "嗨" },
            { en: "goodbye", zh: "再见" },
            { en: "yes", zh: "是" },
            { en: "no", zh: "不" },
            { en: "please", zh: "请" },
            { en: "thank you", zh: "谢谢" },
            { en: "sorry", zh: "对不起" },
            { en: "red", zh: "红色" },
            { en: "blue", zh: "蓝色" },
            { en: "yellow", zh: "黄色" },
            { en: "green", zh: "绿色" },
            { en: "orange", zh: "橙色" },
            { en: "purple", zh: "紫色" },
            { en: "pink", zh: "粉色" },
            { en: "brown", zh: "棕色" },
            { en: "black", zh: "黑色" },
            { en: "white", zh: "白色" },
            { en: "grey", zh: "灰色" },
            { en: "one", zh: "一" },
            { en: "two", zh: "二" },
            { en: "three", zh: "三" },
            { en: "four", zh: "四" },
            { en: "five", zh: "五" },
            { en: "six", zh: "六" },
            { en: "seven", zh: "七" },
            { en: "eight", zh: "八" },
            { en: "nine", zh: "九" },
            { en: "ten", zh: "十" },
            { en: "head", zh: "头" },
            { en: "face", zh: "脸" },
            { en: "eye", zh: "眼睛" },
            { en: "ear", zh: "耳朵" },
            { en: "nose", zh: "鼻子" },
            { en: "mouth", zh: "嘴巴" },
            { en: "hair", zh: "头发" },
            { en: "arm", zh: "手臂" },
            { en: "hand", zh: "手" },
            { en: "leg", zh: "腿" },
            { en: "foot", zh: "脚" },
            { en: "body", zh: "身体" },
            { en: "smile", zh: "微笑" }
          ]
        },
        U1: {
          title: "U1 教室与学校",
          words: [
            { en: "classroom", zh: "教室" },
            { en: "school", zh: "学校" },
            { en: "teacher", zh: "老师" },
            { en: "student", zh: "学生" },
            { en: "rubber", zh: "橡皮" },
            { en: "pencil", zh: "铅笔" },
            { en: "pen", zh: "钢笔" },
            { en: "pencil case", zh: "铅笔盒" },
            { en: "crayon", zh: "蜡笔" },
            { en: "ruler", zh: "尺子" },
            { en: "bag", zh: "书包" },
            { en: "book", zh: "书" },
            { en: "desk", zh: "书桌" },
            { en: "chair", zh: "椅子" },
            { en: "bookcase", zh: "书柜" },
            { en: "cupboard", zh: "橱柜" },
            { en: "window", zh: "窗户" },
            { en: "door", zh: "门" },
            { en: "board", zh: "黑板" },
            { en: "wall", zh: "墙" },
            { en: "floor", zh: "地板" },
            { en: "playground", zh: "操场" },
            { en: "paper", zh: "纸" },
            { en: "picture", zh: "图画" },
            { en: "story", zh: "故事" },
            { en: "word", zh: "单词" },
            { en: "question", zh: "问题" },
            { en: "answer", zh: "答案" },
            { en: "friend", zh: "朋友" },
            { en: "read", zh: "读" },
            { en: "write", zh: "写" },
            { en: "draw", zh: "画画" },
            { en: "listen", zh: "听" },
            { en: "learn", zh: "学习" },
            { en: "help", zh: "帮助" },
            { en: "share", zh: "分享" },
            { en: "quiet", zh: "安静的" },
            { en: "kind", zh: "友善的" }
          ]
        },
        U2: {
          title: "U2 家庭与人物",
          words: [
            { en: "family", zh: "家庭" },
            { en: "mother", zh: "妈妈" },
            { en: "father", zh: "爸爸" },
            { en: "brother", zh: "兄弟" },
            { en: "sister", zh: "姐妹" },
            { en: "grandma", zh: "奶奶" },
            { en: "grandpa", zh: "爷爷" },
            { en: "baby", zh: "婴儿" },
            { en: "boy", zh: "男孩" },
            { en: "girl", zh: "女孩" },
            { en: "man", zh: "男人" },
            { en: "woman", zh: "女人" },
            { en: "child", zh: "小孩" },
            { en: "children", zh: "孩子们" },
            { en: "people", zh: "人们" },
            { en: "young", zh: "年轻的" },
            { en: "old", zh: "年老的" },
            { en: "love", zh: "爱" },
            { en: "live", zh: "居住" },
            { en: "name", zh: "名字" },
            { en: "birthday", zh: "生日" },
            { en: "party", zh: "聚会" },
            { en: "present", zh: "礼物" }
          ]
        },
        U3: {
          title: "U3 玩具与游戏",
          words: [
            { en: "toy", zh: "玩具" },
            { en: "ball", zh: "球" },
            { en: "balloon", zh: "气球" },
            { en: "doll", zh: "娃娃" },
            { en: "kite", zh: "风筝" },
            { en: "robot", zh: "机器人" },
            { en: "teddy bear", zh: "泰迪熊" },
            { en: "game", zh: "游戏" },
            { en: "play", zh: "玩" },
            { en: "jump", zh: "跳" },
            { en: "hop", zh: "单脚跳" },
            { en: "clap", zh: "拍手" },
            { en: "dance", zh: "跳舞" },
            { en: "sing", zh: "唱歌" },
            { en: "throw", zh: "扔" },
            { en: "catch", zh: "接住" },
            { en: "kick", zh: "踢" },
            { en: "box", zh: "盒子" },
            { en: "funny", zh: "滑稽的" },
            { en: "happy", zh: "高兴的" },
            { en: "sad", zh: "伤心的" },
            { en: "new", zh: "新的" },
            { en: "favourite", zh: "最喜欢的" }
          ]
        },
        U4: {
          title: "U4 动物",
          words: [
            { en: "animal", zh: "动物" },
            { en: "cat", zh: "猫" },
            { en: "dog", zh: "狗" },
            { en: "bird", zh: "鸟" },
            { en: "fish", zh: "鱼" },
            { en: "horse", zh: "马" },
            { en: "cow", zh: "奶牛" },
            { en: "sheep", zh: "绵羊" },
            { en: "goat", zh: "山羊" },
            { en: "duck", zh: "鸭子" },
            { en: "chicken", zh: "鸡" },
            { en: "hen", zh: "母鸡" },
            { en: "mouse", zh: "老鼠" },
            { en: "spider", zh: "蜘蛛" },
            { en: "frog", zh: "青蛙" },
            { en: "bee", zh: "蜜蜂" },
            { en: "elephant", zh: "大象" },
            { en: "giraffe", zh: "长颈鹿" },
            { en: "lion", zh: "狮子" },
            { en: "tiger", zh: "老虎" },
            { en: "monkey", zh: "猴子" },
            { en: "snake", zh: "蛇" },
            { en: "bear", zh: "熊" },
            { en: "crocodile", zh: "鳄鱼" },
            { en: "hippo", zh: "河马" },
            { en: "zebra", zh: "斑马" },
            { en: "polar bear", zh: "北极熊" },
            { en: "penguin", zh: "企鹅" },
            { en: "zoo", zh: "动物园" },
            { en: "farm", zh: "农场" },
            { en: "pet", zh: "宠物" },
            { en: "tail", zh: "尾巴" }
          ]
        },
        U5: {
          title: "U5 食物与饮品",
          words: [
            { en: "apple", zh: "苹果" },
            { en: "banana", zh: "香蕉" },
            { en: "pear", zh: "梨" },
            { en: "grapes", zh: "葡萄" },
            { en: "lemon", zh: "柠檬" },
            { en: "mango", zh: "芒果" },
            { en: "watermelon", zh: "西瓜" },
            { en: "coconut", zh: "椰子" },
            { en: "pineapple", zh: "菠萝" },
            { en: "tomato", zh: "西红柿" },
            { en: "potato", zh: "土豆" },
            { en: "carrot", zh: "胡萝卜" },
            { en: "peas", zh: "豌豆" },
            { en: "beans", zh: "豆子" },
            { en: "onion", zh: "洋葱" },
            { en: "bread", zh: "面包" },
            { en: "rice", zh: "米饭" },
            { en: "egg", zh: "鸡蛋" },
            { en: "meat", zh: "肉" },
            { en: "sausage", zh: "香肠" },
            { en: "burger", zh: "汉堡" },
            { en: "chips", zh: "薯条" },
            { en: "pizza", zh: "披萨" },
            { en: "cake", zh: "蛋糕" },
            { en: "ice cream", zh: "冰淇淋" },
            { en: "sweets", zh: "糖果" },
            { en: "chocolate", zh: "巧克力" },
            { en: "biscuit", zh: "饼干" },
            { en: "milk", zh: "牛奶" },
            { en: "water", zh: "水" },
            { en: "juice", zh: "果汁" },
            { en: "lemonade", zh: "柠檬水" },
            { en: "breakfast", zh: "早餐" },
            { en: "lunch", zh: "午餐" },
            { en: "dinner", zh: "晚餐" },
            { en: "eat", zh: "吃" },
            { en: "drink", zh: "喝" },
            { en: "hungry", zh: "饿的" },
            { en: "like", zh: "喜欢" }
          ]
        },
        U6: {
          title: "U6 交通工具",
          words: [
            { en: "bus", zh: "公共汽车" },
            { en: "car", zh: "小汽车" },
            { en: "train", zh: "火车" },
            { en: "plane", zh: "飞机" },
            { en: "boat", zh: "小船" },
            { en: "ship", zh: "轮船" },
            { en: "lorry", zh: "卡车" },
            { en: "motorbike", zh: "摩托车" },
            { en: "helicopter", zh: "直升机" },
            { en: "tractor", zh: "拖拉机" },
            { en: "bike", zh: "自行车" },
            { en: "street", zh: "街道" },
            { en: "stop", zh: "停" },
            { en: "go", zh: "走" },
            { en: "drive", zh: "开车" },
            { en: "ride", zh: "骑" },
            { en: "fly", zh: "飞" },
            { en: "walk", zh: "步行" },
            { en: "fast", zh: "快的" },
            { en: "slow", zh: "慢的" },
            { en: "wheel", zh: "轮子" }
          ]
        },
        U7: {
          title: "U7 运动与音乐",
          words: [
            { en: "sport", zh: "运动" },
            { en: "football", zh: "足球" },
            { en: "basketball", zh: "篮球" },
            { en: "baseball", zh: "棒球" },
            { en: "tennis", zh: "网球" },
            { en: "badminton", zh: "羽毛球" },
            { en: "table tennis", zh: "乒乓球" },
            { en: "hockey", zh: "曲棍球" },
            { en: "swim", zh: "游泳" },
            { en: "run", zh: "跑步" },
            { en: "bounce", zh: "拍球" },
            { en: "music", zh: "音乐" },
            { en: "song", zh: "歌曲" },
            { en: "guitar", zh: "吉他" },
            { en: "piano", zh: "钢琴" },
            { en: "drum", zh: "鼓" }
          ]
        },
        U8: {
          title: "U8 房间与家居",
          words: [
            { en: "house", zh: "房子" },
            { en: "home", zh: "家" },
            { en: "flat", zh: "公寓" },
            { en: "bedroom", zh: "卧室" },
            { en: "bathroom", zh: "浴室" },
            { en: "kitchen", zh: "厨房" },
            { en: "living room", zh: "客厅" },
            { en: "hall", zh: "门厅" },
            { en: "garden", zh: "花园" },
            { en: "bed", zh: "床" },
            { en: "table", zh: "桌子" },
            { en: "sofa", zh: "沙发" },
            { en: "armchair", zh: "扶手椅" },
            { en: "lamp", zh: "台灯" },
            { en: "mirror", zh: "镜子" },
            { en: "clock", zh: "钟" },
            { en: "watch", zh: "手表" },
            { en: "phone", zh: "电话" },
            { en: "TV", zh: "电视" },
            { en: "computer", zh: "电脑" },
            { en: "radio", zh: "收音机" },
            { en: "camera", zh: "照相机" },
            { en: "bath", zh: "浴缸" },
            { en: "keys", zh: "钥匙" },
            { en: "sleep", zh: "睡觉" }
          ]
        },
        U9: {
          title: "U9 衣服与沙滩",
          words: [
            { en: "clothes", zh: "衣服" },
            { en: "T-shirt", zh: "T恤" },
            { en: "shirt", zh: "衬衫" },
            { en: "trousers", zh: "裤子" },
            { en: "jeans", zh: "牛仔裤" },
            { en: "dress", zh: "连衣裙" },
            { en: "skirt", zh: "短裙" },
            { en: "jacket", zh: "夹克" },
            { en: "shoes", zh: "鞋子" },
            { en: "socks", zh: "袜子" },
            { en: "boots", zh: "靴子" },
            { en: "hat", zh: "帽子" },
            { en: "baseball cap", zh: "棒球帽" },
            { en: "glasses", zh: "眼镜" },
            { en: "sunglasses", zh: "太阳镜" },
            { en: "wear", zh: "穿" },
            { en: "beach", zh: "海滩" },
            { en: "sea", zh: "大海" },
            { en: "sand", zh: "沙子" },
            { en: "shell", zh: "贝壳" },
            { en: "sun", zh: "太阳" },
            { en: "jellyfish", zh: "水母" },
            { en: "fishing", zh: "钓鱼" },
            { en: "take photos", zh: "拍照" },
            { en: "pick up", zh: "捡起" },
            { en: "clean", zh: "干净的" },
            { en: "dirty", zh: "脏的" }
          ]
        }
      }
    },
    L2: {
      title: "二级 Level 2",
      units: {
        S: {
          title: "基础：数字与时间",
          words: [
            { en: "eleven", zh: "十一" },
            { en: "twelve", zh: "十二" },
            { en: "thirteen", zh: "十三" },
            { en: "fourteen", zh: "十四" },
            { en: "fifteen", zh: "十五" },
            { en: "sixteen", zh: "十六" },
            { en: "seventeen", zh: "十七" },
            { en: "eighteen", zh: "十八" },
            { en: "nineteen", zh: "十九" },
            { en: "twenty", zh: "二十" },
            { en: "thirty", zh: "三十" },
            { en: "forty", zh: "四十" },
            { en: "fifty", zh: "五十" },
            { en: "hundred", zh: "一百" },
            { en: "first", zh: "第一" },
            { en: "second", zh: "第二" },
            { en: "third", zh: "第三" },
            { en: "today", zh: "今天" },
            { en: "yesterday", zh: "昨天" },
            { en: "tomorrow", zh: "明天" },
            { en: "morning", zh: "早上" },
            { en: "afternoon", zh: "下午" },
            { en: "evening", zh: "傍晚" },
            { en: "night", zh: "夜晚" },
            { en: "week", zh: "星期" },
            { en: "weekend", zh: "周末" },
            { en: "month", zh: "月份" },
            { en: "year", zh: "年" },
            { en: "o'clock", zh: "点钟" }
          ]
        },
        U1: {
          title: "U1 乡村与自然",
          words: [
            { en: "countryside", zh: "乡村" },
            { en: "forest", zh: "森林" },
            { en: "lake", zh: "湖" },
            { en: "river", zh: "河流" },
            { en: "mountain", zh: "山" },
            { en: "field", zh: "田野" },
            { en: "grass", zh: "草地" },
            { en: "flower", zh: "花" },
            { en: "tree", zh: "树" },
            { en: "leaf", zh: "树叶" },
            { en: "plant", zh: "植物" },
            { en: "waterfall", zh: "瀑布" },
            { en: "island", zh: "岛" },
            { en: "rock", zh: "岩石" },
            { en: "picnic", zh: "野餐" },
            { en: "village", zh: "村庄" },
            { en: "path", zh: "小路" },
            { en: "sky", zh: "天空" },
            { en: "star", zh: "星星" },
            { en: "moon", zh: "月亮" }
          ]
        },
        U2: {
          title: "U2 星期与日常",
          words: [
            { en: "Monday", zh: "星期一" },
            { en: "Tuesday", zh: "星期二" },
            { en: "Wednesday", zh: "星期三" },
            { en: "Thursday", zh: "星期四" },
            { en: "Friday", zh: "星期五" },
            { en: "Saturday", zh: "星期六" },
            { en: "Sunday", zh: "星期日" },
            { en: "get up", zh: "起床" },
            { en: "go to bed", zh: "上床睡觉" },
            { en: "brush my teeth", zh: "刷牙" },
            { en: "wash my face", zh: "洗脸" },
            { en: "have breakfast", zh: "吃早餐" },
            { en: "go to school", zh: "上学" },
            { en: "do homework", zh: "做作业" },
            { en: "homework", zh: "作业" },
            { en: "before", zh: "在…之前" },
            { en: "after", zh: "在…之后" },
            { en: "every day", zh: "每天" },
            { en: "always", zh: "总是" },
            { en: "sometimes", zh: "有时" },
            { en: "never", zh: "从不" }
          ]
        },
        U3: {
          title: "U3 工作与职业",
          words: [
            { en: "job", zh: "职业" },
            { en: "work", zh: "工作" },
            { en: "doctor", zh: "医生" },
            { en: "nurse", zh: "护士" },
            { en: "farmer", zh: "农民" },
            { en: "cook", zh: "厨师" },
            { en: "driver", zh: "司机" },
            { en: "police officer", zh: "警察" },
            { en: "firefighter", zh: "消防员" },
            { en: "dentist", zh: "牙医" },
            { en: "pirate", zh: "海盗" },
            { en: "clown", zh: "小丑" },
            { en: "film star", zh: "电影明星" },
            { en: "pop star", zh: "流行歌星" },
            { en: "hospital", zh: "医院" },
            { en: "police station", zh: "警察局" },
            { en: "fire station", zh: "消防站" }
          ]
        },
        U4: {
          title: "U4 我的家",
          words: [
            { en: "address", zh: "地址" },
            { en: "balcony", zh: "阳台" },
            { en: "basement", zh: "地下室" },
            { en: "lift", zh: "电梯" },
            { en: "stairs", zh: "楼梯" },
            { en: "roof", zh: "屋顶" },
            { en: "blanket", zh: "毯子" },
            { en: "pillow", zh: "枕头" },
            { en: "towel", zh: "毛巾" },
            { en: "soap", zh: "肥皂" },
            { en: "toothbrush", zh: "牙刷" },
            { en: "toothpaste", zh: "牙膏" },
            { en: "cup", zh: "杯子" },
            { en: "glass", zh: "玻璃杯" },
            { en: "plate", zh: "盘子" },
            { en: "bowl", zh: "碗" },
            { en: "knife", zh: "刀" },
            { en: "fork", zh: "叉子" },
            { en: "spoon", zh: "勺子" },
            { en: "bottle", zh: "瓶子" },
            { en: "shower", zh: "淋浴" }
          ]
        },
        U5: {
          title: "U5 野生动物",
          words: [
            { en: "wild", zh: "野生的" },
            { en: "panda", zh: "熊猫" },
            { en: "kangaroo", zh: "袋鼠" },
            { en: "whale", zh: "鲸鱼" },
            { en: "dolphin", zh: "海豚" },
            { en: "shark", zh: "鲨鱼" },
            { en: "bat", zh: "蝙蝠" },
            { en: "snail", zh: "蜗牛" },
            { en: "rabbit", zh: "兔子" },
            { en: "parrot", zh: "鹦鹉" },
            { en: "lizard", zh: "蜥蜴" },
            { en: "jungle", zh: "丛林" },
            { en: "climb", zh: "爬" },
            { en: "feed", zh: "喂" },
            { en: "dangerous", zh: "危险的" }
          ]
        },
        U6: {
          title: "U6 天气与季节",
          words: [
            { en: "weather", zh: "天气" },
            { en: "sunny", zh: "晴朗的" },
            { en: "cloudy", zh: "多云的" },
            { en: "rainy", zh: "下雨的" },
            { en: "windy", zh: "有风的" },
            { en: "snowy", zh: "下雪的" },
            { en: "rain", zh: "雨" },
            { en: "snow", zh: "雪" },
            { en: "wind", zh: "风" },
            { en: "cloud", zh: "云" },
            { en: "rainbow", zh: "彩虹" },
            { en: "hot", zh: "热的" },
            { en: "cold", zh: "冷的" },
            { en: "warm", zh: "温暖的" },
            { en: "cool", zh: "凉爽的" },
            { en: "ice", zh: "冰" },
            { en: "coat", zh: "外套" },
            { en: "scarf", zh: "围巾" },
            { en: "sweater", zh: "毛衣" },
            { en: "umbrella", zh: "雨伞" },
            { en: "season", zh: "季节" },
            { en: "spring", zh: "春天" },
            { en: "summer", zh: "夏天" },
            { en: "autumn", zh: "秋天" },
            { en: "winter", zh: "冬天" }
          ]
        },
        U7: {
          title: "U7 城市与出行",
          words: [
            { en: "city", zh: "城市" },
            { en: "town", zh: "城镇" },
            { en: "shop", zh: "商店" },
            { en: "supermarket", zh: "超市" },
            { en: "market", zh: "市场" },
            { en: "cinema", zh: "电影院" },
            { en: "library", zh: "图书馆" },
            { en: "park", zh: "公园" },
            { en: "cafe", zh: "咖啡馆" },
            { en: "swimming pool", zh: "游泳池" },
            { en: "funfair", zh: "游乐场" },
            { en: "station", zh: "车站" },
            { en: "bus stop", zh: "公交车站" },
            { en: "ticket", zh: "票" },
            { en: "trip", zh: "旅行" },
            { en: "holiday", zh: "假期" },
            { en: "visit", zh: "参观" },
            { en: "buy", zh: "买" },
            { en: "money", zh: "钱" },
            { en: "map", zh: "地图" }
          ]
        },
        U8: {
          title: "U8 描述与比较",
          words: [
            { en: "big", zh: "大的" },
            { en: "small", zh: "小的" },
            { en: "tall", zh: "高的" },
            { en: "short", zh: "矮的" },
            { en: "long", zh: "长的" },
            { en: "thin", zh: "瘦的" },
            { en: "fat", zh: "胖的" },
            { en: "beautiful", zh: "美丽的" },
            { en: "strong", zh: "强壮的" },
            { en: "quick", zh: "迅速的" },
            { en: "loud", zh: "大声的" },
            { en: "naughty", zh: "淘气的" },
            { en: "brave", zh: "勇敢的" },
            { en: "clever", zh: "聪明的" },
            { en: "tired", zh: "累的" },
            { en: "thirsty", zh: "渴的" },
            { en: "angry", zh: "生气的" },
            { en: "afraid", zh: "害怕的" },
            { en: "surprised", zh: "惊讶的" },
            { en: "better", zh: "更好的" },
            { en: "best", zh: "最好的" },
            { en: "different", zh: "不同的" },
            { en: "same", zh: "相同的" },
            { en: "easy", zh: "容易的" },
            { en: "difficult", zh: "困难的" }
          ]
        },
        U9: {
          title: "U9 食物与健康",
          words: [
            { en: "cheese", zh: "奶酪" },
            { en: "tea", zh: "茶" },
            { en: "coffee", zh: "咖啡" },
            { en: "soup", zh: "汤" },
            { en: "salad", zh: "沙拉" },
            { en: "sandwich", zh: "三明治" },
            { en: "pasta", zh: "意大利面" },
            { en: "noodles", zh: "面条" },
            { en: "vegetables", zh: "蔬菜" },
            { en: "fruit", zh: "水果" },
            { en: "kiwi", zh: "猕猴桃" },
            { en: "pancake", zh: "薄煎饼" },
            { en: "milkshake", zh: "奶昔" },
            { en: "jam", zh: "果酱" },
            { en: "shoulder", zh: "肩膀" },
            { en: "back", zh: "背部" },
            { en: "stomach", zh: "肚子" },
            { en: "neck", zh: "脖子" },
            { en: "tooth", zh: "牙齿" },
            { en: "headache", zh: "头痛" },
            { en: "stomachache", zh: "肚子痛" },
            { en: "cough", zh: "咳嗽" },
            { en: "temperature", zh: "发烧" },
            { en: "hurt", zh: "疼" },
            { en: "ill", zh: "生病的" },
            { en: "have a cold", zh: "感冒" }
          ]
        }
      }
    }
  };

  root.WORD_BANK = WORD_BANK;
  if (typeof module !== "undefined" && module.exports) {
    module.exports = WORD_BANK;
  }
})(typeof window !== "undefined" ? window : this);
